In [2]:
import numpy as np

In [4]:
array_of_ones = np.ones((4,5))
                                 #(x,y) ==>x is row y is columns
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
type(array_of_ones)

numpy.ndarray

In [ ]:
note: internally numpy will be considering the float datatype

In [ ]:
req: to remove the dots...!

In [7]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [8]:
array_empty = np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
python---->range(1,20,2)

In [ ]:
numpy----->arange

In [ ]:
req:to print the even num from 2,20 in numpy

In [10]:
array_of_evens = np.arange(2,20,2) #last value is always exclusive
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
array_of_floats = np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
nd array-----> n dimensional arrays..

In [ ]:
Two dimensional arrays:

In [13]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d.shape #(x,y)====>2 dimensional

(2, 3)